version: "2"
services:
  mysql:
    image: mysql:8.3
    ports:
      - "3307:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "%bZpkGJJnQrA6$Dd"
      MYSQL_DATABASE: Movies
      MYSQL_USER: user
      MYSQL_PASSWORD: userPassword

volumes:
  mysql_data:
    driver: local